
name: hello-world-app-ci

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with: 
          python-version: "3.x"

      - name: Install package deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi;
      
      - name: Run the application.
        run: |
          python ./main.py
